/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IARWSupply,
  IARWSupplyInterface,
} from "../../../../contracts/interfaces/IARWSupply.sol/IARWSupply.js";

const _abi = [
  {
    inputs: [],
    name: "circulatingSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "excludedAddresses",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "excludedSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IARWSupply__factory {
  static readonly abi = _abi;
  static createInterface(): IARWSupplyInterface {
    return new Interface(_abi) as IARWSupplyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IARWSupply {
    return new Contract(address, _abi, runner) as unknown as IARWSupply;
  }
}
