/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common.js";

export interface IARWSupplyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "circulatingSupply"
      | "excludedAddresses"
      | "excludedSupply",
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "circulatingSupply",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "excludedAddresses",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "excludedSupply",
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: "circulatingSupply",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludedAddresses",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "excludedSupply",
    data: BytesLike,
  ): Result;
}

export interface IARWSupply extends BaseContract {
  connect(runner?: ContractRunner | null): IARWSupply;
  waitForDeployment(): Promise<this>;

  interface: IARWSupplyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  circulatingSupply: TypedContractMethod<[], [bigint], "view">;

  excludedAddresses: TypedContractMethod<[], [string[]], "view">;

  excludedSupply: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: "circulatingSupply",
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "excludedAddresses",
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "excludedSupply",
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
